#ifndef AXI_ETHERNET_MAC_LITE_HPP
#define AXI_ETHERNET_MAC_LITE_HPP

#define TX_PING_DATA_OFFSET 0x0
#define MDIO_ADDR_OFFSET    0x07e4
#define MDIO_WR_OFFSET      0x07e8
#define MDIO_RD_OFFSET      0x07ec
#define MDIO_CTRL_OFFSET    0x07f0
#define TX_PING_LEN_OFFSET  0x07f4
#define GIE_OFFSET          0x07f8
#define TX_PING_CTRL_OFFSET 0x07fc
#define TX_PONG_DATA_OFFSET 0x0800
#define TX_PONG_LEN_OFFSET  0x0ff4
#define TX_PONG_CTRL_OFFSET 0x0ffc
#define RX_PING_DATA_OFFSET 0x1000
#define RX_PING_CTRL_OFFSET 0x17fc
#define RX_PONG_DATA_OFFSET 0x1800
#define RX_PONG_CTRL_OFFSET 0x1ffc

#define ETH_DST_ADDR_OFFSET 0
#define ETH_SRC_ADDR_OFFSET 6
#define ETH_TYPE_OFFSET     12
#define IP_VER_IHL_OFFSET   14
#define IP_TYPE_OFFSET      15
#define IP_LEN_OFFSET       16
#define IP_ID_OFFSET        18
#define IP_FRAGMENT_OFFSET  20
#define IP_TTL_OFFSET       22
#define IP_PROTOCOL_OFFSET  23
#define IP_CHECKSUM_OFFSET  24
#define IP_SRC_ADDR_OFFSET  26
#define IP_DST_ADDR_OFFSET  30
#define UDP_SRC_PORT_OFFSET 34
#define UDP_DST_PORT_OFFSET 36
#define UDP_LEN_OFFSET      38
#define UDP_CHECKSUM_OFFSET 40
#define UDP_PAYLOAD_OFFSET  42

#define LEN_IP_UDP_HEADER   28

#endif
